apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: microservices
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: microservices-api-gateway/product-service:latest
          ports:
            - containerPort: 3002
          env:
            - name: PORT
              value: "3002"
            - name: NODE_ENV
              value: production
            - name: PRODUCT_DB_URL
              value: postgresql://postgres:$(POSTGRES_PASSWORD)@postgres:5432/products_db
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: microservices-secrets
                  key: POSTGRES_PASSWORD
            - name: NATS_URL
              value: nats://nats:4222
            - name: GATEWAY_SECRET
              valueFrom:
                secretKeyRef:
                  name: microservices-secrets
                  key: GATEWAY_SECRET
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://jaeger:4318
            - name: OTEL_SERVICE_NAME
              value: product-service
            - name: OTEL_SERVICE_VERSION
              value: "1.0.0"
            - name: OTEL_TRACES_SAMPLER_RATIO
              value: "1"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 10
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 30
            periodSeconds: 5
            failureThreshold: 10
