apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: microservices
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: microservices-api-gateway/gateway:latest
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: NODE_ENV
              value: production
            - name: TRUST_PROXY
              value: "true"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: microservices-secrets
                  key: JWT_SECRET
            - name: JWT_ISSUER
              value: "microservices-api-gateway"
            - name: JWT_AUDIENCE
              value: "microservices-api-gateway"
            - name: GATEWAY_SECRET
              valueFrom:
                secretKeyRef:
                  name: microservices-secrets
                  key: GATEWAY_SECRET
            - name: REDIS_URL
              value: redis://redis:6379
            - name: NATS_URL
              value: nats://nats:4222
            - name: USER_SERVICE_URL
              value: http://user-service:3001
            - name: PRODUCT_SERVICE_URL
              value: http://product-service:3002
            - name: ORDER_SERVICE_URL
              value: http://order-service:3003
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://jaeger:4318
            - name: OTEL_SERVICE_NAME
              value: gateway
            - name: OTEL_SERVICE_VERSION
              value: "1.0.0"
            - name: OTEL_TRACES_SAMPLER_RATIO
              value: "1"
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health/live
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /health/live
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 5
            failureThreshold: 10
