FROM node:20-alpine

WORKDIR /app

COPY package.json ./
COPY shared/package.json ./shared/
COPY services/order-service/package.json ./services/order-service/

RUN npm install --workspace=shared --workspace=services/order-service

COPY shared/ ./shared/
COPY services/order-service/ ./services/order-service/
COPY tsconfig.base.json ./

RUN cd services/order-service && npx prisma generate

EXPOSE 3003

CMD ["npm", "run", "dev:order"]
